import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Poppins } from 'next/font/google';
import "./globals.css";
import { AppWrapper } from '../context/index';
const poppins = Poppins({
  subsets: ['latin'], // Specify the character subset you need
  variable: '--font-poppins', // Optional CSS variable for the font
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // Include the weights you want
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppWrapper>
      <html lang='en'>
        <body className={poppins.variable}>{children}</body>
      </html>
    </AppWrapper>
  );
}
